# Generated by Django 6.0.7 on 2026-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
