# Generated by Django 6.0.7 on 2026-07-11 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_master_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterPortfolioPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_portfolio_photos', to='user.master')),
            ],
            options={
                'verbose_name': 'Master Portfolio Photos',
                'verbose_name_plural': 'Master Portfolio Photos',
                'ordering': ['-created_at'],
            },
        ),
    ]
